var gvjs_AO="Invalid state: should be an array of values.",gvjs_BO="No valid DataTable received from draw()",gvjs_CO="Start and end points must be 2D",gvjs_DO="goog-combobox-active",gvjs_EO="goog-flat-button",gvjs_FO="goog-link-button",gvjs_GO="aside",gvjs_HO="belowStacked",gvjs_IO="blockIncrement",gvjs_JO="google-visualization-controls-rangefilter",gvjs_KO="month",gvjs_LO="placeholder",gvjs_MO="uichange",gvjs_NO="useFormattedValue",gvjs_OO="yy/MM/dd hh:mma";
gvjs_DB.prototype.yq=gvjs_B(54,function(a){this.PA=a});gvjs_FD.prototype.yq=gvjs_B(53,function(a){this.PA=a});gvjs_J.prototype.Cg=gvjs_B(19,function(){return this.Rg});function gvjs_PO(a){return new gvjs_C(a.offsetLeft,a.offsetTop)}function gvjs_QO(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];gvjs_rb(d)?gvjs_QO.apply(null,d):gvjs_K(d)}}function gvjs_RO(a){gvjs_J.call(this);this.ha=a;this.ba=new gvjs_hz(this)}gvjs_l(gvjs_RO,gvjs_J);gvjs_=gvjs_RO.prototype;
gvjs_.O=function(){this.clear();gvjs_RO.o.O.call(this)};gvjs_.clear=function(){this.ba.removeAll();gvjs_K(this.ba);gvjs_Pc(this.ha)};gvjs_.getContainer=function(){return this.ha};gvjs_.addEventListener=function(a,b,c,d,e){e?gvjs_iz(this.ba,a,b,c,d,e):this.ba.D(a,b,c,d)};gvjs_.draw=function(){};gvjs_.getState=function(){return{}};function gvjs_SO(a){gvjs_P.call(this,a);this.l8=[]}gvjs_l(gvjs_SO,gvjs_P);gvjs_=gvjs_SO.prototype;gvjs_.O=function(){this.clear();gvjs_SO.o.O.call(this)};gvjs_.clear=function(){this.nf()};
gvjs_.nf=function(){this.tL&&(gvjs_2k(this.tL),gvjs_K(this.tL),this.tL=null);gvjs_K(this.Uc);this.Uc=null;gvjs_Pc(this.container)};gvjs_.qa=null;gvjs_.yu=null;gvjs_.m=null;gvjs_.Uc=null;gvjs_.tL=null;gvjs_.G4=null;gvjs_.K=null;gvjs_.Rv=null;gvjs_.Wa=function(){return this.qa};gvjs_.cd=function(){return this.m};gvjs_.Of=function(){return{}};gvjs_.em=function(a,b){return gvjs_Zw(b,"ui",{})};gvjs_.gt=function(){return""};gvjs_.Vea=function(a){this.l8=a};gvjs_.BO=function(){return this.l8};gvjs_.pr=function(){};
gvjs_.getState=function(){return this.K?gvjs_Ii(gvjs_Gi(this.K)):null};gvjs_.draw=function(a,b,c){gvjs_jl(a);this.qa=a;this.yu=b||{};this.G4=c||{};gvjs_ol(this.Ho,this.UB,this)};
gvjs_.UB=function(){if(this.qa){this.K=this.G4||{};if(!gvjs_i(this.K))throw Error("Control state must be an object.");this.Rv=this.Rv||this.K;this.m=new gvjs_qd([this.yu,this.Of()||{}]);this.pr(this.qa,this.m,this.K);if(!this.Uc){var a=gvjs_r(this.m,"ui.type",this.gt());this.Zt&&(a=gvjs_5m(a));this.Uc=(a=gvjs_tk(a))?new a(this.container):null;if(!this.Uc)throw Error("Invalid Ui instance.");this.tL=gvjs_Xk(this.Uc,gvjs_MO,gvjs_k(this.xya,this))}this.Uc.draw(this.K,this.em(this.qa,this.m));this.K=this.Uc.getState();
gvjs_M(this,gvjs_x,null)}};gvjs_.xya=function(a){this.K=this.Uc.getState();gvjs_M(this,gvjs_Zg,a)};gvjs_.Yt=function(){gvjs_ol(this.Ho,this.Cva,this)};gvjs_.Cva=function(){this.Rv&&(this.G4=this.Rv,this.UB())};
function gvjs_Qia(a){if(a.altKey&&!a.ctrlKey||a.metaKey||112<=a.keyCode&&123>=a.keyCode)return!1;if(gvjs_Iz(a.keyCode))return!0;switch(a.keyCode){case 18:case 20:case 93:case 17:case 40:case 35:case 27:case 36:case 45:case 37:case 224:case 91:case 144:case 12:case 34:case 33:case 19:case 255:case 44:case 39:case 145:case 16:case 38:case 252:case 224:case 92:return!1;case 0:return!gvjs_nc;default:return 166>a.keyCode||183<a.keyCode}}function gvjs_TO(){gvjs_ED.call(this);this.qr=[]}gvjs_l(gvjs_TO,gvjs_ED);
gvjs_TO.prototype.add=function(a){gvjs_Db(this.qr,a)||(this.qr.push(a),gvjs_L(a,gvjs_5r,this.Gca,!1,this))};gvjs_TO.prototype.remove=function(a){gvjs_Vh(this.qr,a)&&gvjs_Pk(a,gvjs_5r,this.Gca,!1,this)};gvjs_TO.prototype.O=function(){gvjs_m(this.qr,function(a){a.na()});this.qr.length=0;gvjs_TO.o.O.call(this)};function gvjs_UO(){gvjs_TO.call(this);this.EX=0}gvjs_l(gvjs_UO,gvjs_TO);
gvjs_UO.prototype.play=function(a){if(0==this.qr.length)return!1;if(a||0==this.K)this.EX=0,this.IJ();else if(this.bp())return!1;this.Th("play");-1==this.K&&this.Th("resume");var b=-1==this.K&&!a;this.startTime=gvjs_vb();this.endTime=null;this.K=1;gvjs_m(this.qr,function(c){b&&-1!=c.K||c.play(a)});return!0};gvjs_UO.prototype.pause=function(){this.bp()&&(gvjs_m(this.qr,function(a){a.bp()&&a.pause()}),this.K=-1,this.Th("pause"))};
gvjs_UO.prototype.stop=function(a){gvjs_m(this.qr,function(b){0==b.K||b.stop(a)});this.K=0;this.endTime=gvjs_vb();this.Th(gvjs_mv);this.Hz()};gvjs_UO.prototype.Gca=function(){this.EX++;this.EX==this.qr.length&&(this.endTime=gvjs_vb(),this.K=0,this.Th(gvjs_5r),this.Hz())};function gvjs_VO(a,b,c,d,e){gvjs_FD.call(this,b,c,d,e);this.element=a}gvjs_l(gvjs_VO,gvjs_FD);gvjs_=gvjs_VO.prototype;gvjs_.OA=gvjs_pb;gvjs_.wh=function(){void 0===this.ur&&(this.ur=gvjs_1y(this.element));return this.ur};
gvjs_.C0=function(){this.OA();gvjs_VO.o.C0.call(this)};gvjs_.Hz=function(){this.OA();gvjs_VO.o.Hz.call(this)};gvjs_.IJ=function(){this.OA();gvjs_VO.o.IJ.call(this)};function gvjs_WO(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error(gvjs_CO);gvjs_VO.call(this,a,b,c,d,e)}gvjs_l(gvjs_WO,gvjs_VO);gvjs_WO.prototype.OA=function(){var a=this.PA&&this.wh()?gvjs_y:gvjs_zg;this.element.style[a]=Math.round(this.coords[0])+gvjs__;this.element.style.top=Math.round(this.coords[1])+gvjs__};
function gvjs_XO(a,b,c,d,e){gvjs_VO.call(this,a,[b],[c],d,e)}gvjs_l(gvjs_XO,gvjs_VO);gvjs_XO.prototype.OA=function(){this.element.style.width=Math.round(this.coords[0])+gvjs__};function gvjs_YO(a,b,c,d,e){gvjs_VO.call(this,a,[b],[c],d,e)}gvjs_l(gvjs_YO,gvjs_VO);gvjs_YO.prototype.OA=function(){this.element.style.height=Math.round(this.coords[0])+gvjs__};function gvjs_ZO(){gvjs_Vk.call(this)}gvjs_l(gvjs_ZO,gvjs_Vk);gvjs_=gvjs_ZO.prototype;gvjs_.de=0;gvjs_.kp=0;gvjs_.Hn=100;gvjs_.Ul=0;gvjs_.Bj=1;
gvjs_.hl=!1;gvjs_.zz=!1;gvjs_.Va=function(a){a=gvjs__O(this,a);this.de!=a&&(this.de=a+this.Ul>this.Hn?this.Hn-this.Ul:a<this.kp?this.kp:a,this.hl||this.zz||this.dispatchEvent(gvjs_Jq))};gvjs_.getValue=function(){return gvjs__O(this,this.de)};gvjs_.FS=function(a){a=gvjs__O(this,a);this.Ul!=a&&(this.Ul=0>a?0:this.de+a>this.Hn?this.Hn-this.de:a,this.hl||this.zz||this.dispatchEvent(gvjs_Jq))};gvjs_.am=function(){var a=this.Ul;return null==this.Bj?a:Math.round(a/this.Bj)*this.Bj};
gvjs_.Fw=function(a){if(this.kp!=a){var b=this.hl;this.hl=!0;this.kp=a;a+this.Ul>this.Hn&&(this.Ul=this.Hn-this.kp);a>this.de&&this.Va(a);a>this.Hn&&(this.Ul=0,this.ku(a),this.Va(a));(this.hl=b)||this.zz||this.dispatchEvent(gvjs_Jq)}};gvjs_.yf=function(){return gvjs__O(this,this.kp)};
gvjs_.ku=function(a){a=gvjs__O(this,a);if(this.Hn!=a){var b=this.hl;this.hl=!0;this.Hn=a;a<this.de+this.Ul&&this.Va(a-this.Ul);a<this.kp&&(this.Ul=0,this.Fw(a),this.Va(this.Hn));a<this.kp+this.Ul&&(this.Ul=this.Hn-this.kp);(this.hl=b)||this.zz||this.dispatchEvent(gvjs_Jq)}};gvjs_.xf=function(){return gvjs__O(this,this.Hn)};gvjs_.XH=function(){return this.Bj};
gvjs_.SS=function(a){this.Bj!=a&&(this.Bj=a,a=this.hl,this.hl=!0,this.ku(this.xf()),this.FS(this.am()),this.Va(this.getValue()),(this.hl=a)||this.zz||this.dispatchEvent(gvjs_Jq))};function gvjs__O(a,b){return null==a.Bj?b:a.kp+Math.round((b-a.kp)/a.Bj)*a.Bj}function gvjs_0O(a,b){gvjs_pB.call(this,a);this.J5=null;this.af=new gvjs_ZO;this.tsa=b||gvjs_1h;this.Una=!0;gvjs_L(this.af,gvjs_Jq,this.C$,!1,this)}gvjs_l(gvjs_0O,gvjs_pB);gvjs_=gvjs_0O.prototype;gvjs_.rb=gvjs_Z;gvjs_.GP=!1;gvjs_.h0=!1;
gvjs_.Rm=10;gvjs_.HQ=0;gvjs_.Haa=!0;gvjs_.fca=0;gvjs_.Fia=1E3;gvjs_.yg=!0;gvjs_.Vl=!1;gvjs_.J=function(){gvjs_0O.o.J.call(this);var a=this.xa().J(gvjs_v,this.ra(this.rb));this.Lf(a)};
gvjs_.Lf=function(a){gvjs_0O.o.Lf.call(this,a);gvjs_yB(a,this.ra(this.rb));a=this.j();var b=this.xa().J(gvjs_v,"google-visualization-controls-slider-handle");gvjs_mA(b,gvjs_Aq);this.XB=b;a.appendChild(this.XB);this.Pd=gvjs_1O(this);a.appendChild(this.Pd);this.gj=gvjs_1O(this);a.appendChild(this.gj);a=this.j();gvjs_mA(a,"slider");gvjs_2O(this)};
gvjs_.Ob=function(){gvjs_0O.o.Ob.call(this);this.Mm=new gvjs_DB(this.Pd);this.zq=new gvjs_DB(this.gj);this.Mm.yq(this.Vl);this.zq.yq(this.Vl);this.Mm.Zx=this.zq.Zx=gvjs_pb;this.Vf=new gvjs_7B(this.j());gvjs_3O(this,!0);this.j().tabIndex=0;gvjs_4O(this)};
function gvjs_3O(a,b){b?(a.kc().D(a.Mm,gvjs_kq,a.XO).D(a.zq,gvjs_kq,a.XO).D(a.Mm,[gvjs_0,gvjs_Y],a.Hv).D(a.zq,[gvjs_0,gvjs_Y],a.Hv).D(a.Vf,gvjs_9s,a.zn).D(a.j(),gvjs_0q,a.$O).D(a.j(),gvjs_Fg,a.$O),a.Haa&&gvjs_5O(a,!0)):(a.kc().zb(a.Mm,gvjs_kq,a.XO).zb(a.zq,gvjs_kq,a.XO).zb(a.Mm,[gvjs_0,gvjs_Y],a.Hv).zb(a.zq,[gvjs_0,gvjs_Y],a.Hv).zb(a.Vf,gvjs_9s,a.zn).zb(a.j(),gvjs_0q,a.$O).zb(a.j(),gvjs_Fg,a.$O),a.Haa&&gvjs_5O(a,!1))}gvjs_.Ue=function(){gvjs_0O.o.Ue.call(this);gvjs_QO(this.Mm,this.zq,this.Vf,this.In)};
gvjs_.XO=function(a){var b=a.gX==this.Mm?this.Pd:this.gj;if(this.rb==gvjs_1){var c=this.j().clientHeight-b.offsetHeight;c=(c-a.top)/c*(this.xf()-this.yf())+this.yf()}else c=this.j().clientWidth-b.offsetWidth,c=a.left/c*(this.xf()-this.yf())+this.yf();c=a.gX==this.Mm?Math.min(Math.max(c,this.yf()),this.getValue()+this.am()):Math.min(Math.max(c,this.getValue()),this.xf());gvjs_6O(this,b,c)};
gvjs_.Hv=function(a){var b=a.type==gvjs_0;gvjs_CB(this.j(),"goog-slider-dragging",b);gvjs_CB(a.target.AC,"goog-slider-thumb-dragging",b);a=a.gX==this.Mm;b?(this.dispatchEvent("e"),this.dispatchEvent(a?"a":"c")):(this.dispatchEvent("f"),this.dispatchEvent(a?"b":"d"))};
gvjs_.zn=function(a){var b=!0;switch(a.keyCode){case 36:gvjs_7O(this,this.yf());break;case 35:gvjs_7O(this,this.xf());break;case 33:gvjs_8O(this,this.Rm);break;case 34:gvjs_8O(this,-this.Rm);break;case 37:var c=this.Vl&&this.wh()?1:-1;gvjs_8O(this,a.shiftKey?c*this.Rm:c*this.LA);break;case 40:gvjs_8O(this,a.shiftKey?-this.Rm:-this.LA);break;case 39:c=this.Vl&&this.wh()?-1:1;gvjs_8O(this,a.shiftKey?c*this.Rm:c*this.LA);break;case 38:gvjs_8O(this,a.shiftKey?this.Rm:this.LA);break;default:b=!1}b&&a.preventDefault()};
gvjs_.$O=function(a){this.Una&&this.j().focus&&this.j().focus();var b=a.target;gvjs_Zc(this.Pd,b)||gvjs_Zc(this.gj,b)||(b=a.type==gvjs_0q,b&&gvjs_vb()<this.fca+this.Fia||(b||(this.fca=gvjs_vb()),this.h0?gvjs_7O(this,gvjs_9O(this,a)):(this.A3(a),this.ao=gvjs_$O(this,gvjs_9O(this,a)),this.naa=this.rb==gvjs_1?this.mz<this.ao.offsetTop:this.mz>gvjs_aP(this,this.ao)+this.ao.offsetWidth,a=gvjs_Hc(this.j()),this.kc().D(a,gvjs_Lg,this.y3,!0).D(this.j(),gvjs_Ig,this.A3),this.Qv||(this.Qv=new gvjs_dz(200),
this.kc().D(this.Qv,gvjs_Gv,this.I$)),this.I$(),this.Qv.start())))};gvjs_.y$=function(a){gvjs_8O(this,(0<a.detail?-1:1)*this.LA);a.preventDefault()};
gvjs_.I$=function(){var a;if(this.rb==gvjs_1){var b=this.mz,c=this.ao.offsetTop;this.naa?b<c&&(a=gvjs_bP(this,this.ao)+this.Rm):b>c+this.ao.offsetHeight&&(a=gvjs_bP(this,this.ao)-this.Rm)}else b=this.mz,c=gvjs_aP(this,this.ao),this.naa?b>c+this.ao.offsetWidth&&(a=gvjs_bP(this,this.ao)+this.Rm):b<c&&(a=gvjs_bP(this,this.ao)-this.Rm);void 0!==a&&gvjs_6O(this,this.ao,a)};gvjs_.y3=function(){this.Qv&&this.Qv.stop();var a=gvjs_Hc(this.j());this.kc().zb(a,gvjs_Lg,this.y3,!0).zb(this.j(),gvjs_Ig,this.A3)};
function gvjs_cP(a,b){b=gvjs_Wy(b,a.j());return a.rb==gvjs_1?b.y:a.Vl&&a.wh()?a.j().clientWidth-b.x:b.x}gvjs_.A3=function(a){this.mz=gvjs_cP(this,a)};function gvjs_9O(a,b){var c=a.yf(),d=a.xf();if(a.rb==gvjs_1){var e=a.Pd.offsetHeight,f=a.j().clientHeight-e;a=gvjs_cP(a,b)-e/2;return(d-c)*(f-a)/f+c}e=a.Pd.offsetWidth;f=a.j().clientWidth-e;a=gvjs_cP(a,b)-e/2;return(d-c)*a/f+c}
function gvjs_bP(a,b){if(b==a.Pd)return a.af.getValue();if(b==a.gj)return a.af.getValue()+a.af.am();throw Error("Illegal thumb element. Neither minThumb nor maxThumb");}function gvjs_8O(a,b){Math.abs(b)<a.XH()&&(b=gvjs_0x(b)*a.XH());var c=gvjs_bP(a,a.Pd)+b;b=gvjs_bP(a,a.gj)+b;c=gvjs_Ec(c,a.yf(),a.xf()-a.HQ);b=gvjs_Ec(b,a.yf()+a.HQ,a.xf());gvjs_dP(a,c,b-c)}
function gvjs_6O(a,b,c){var d=gvjs__O(a.af,c);c=b==a.Pd?d:a.af.getValue();b=b==a.gj?d:a.af.getValue()+a.af.am();c>=a.yf()&&b>=c+a.HQ&&a.xf()>=b&&gvjs_dP(a,c,b-c)}function gvjs_dP(a,b,c){a.yf()<=b&&b<=a.xf()-c&&a.HQ<=c&&c<=a.xf()-b&&(b!=a.getValue()||c!=a.am())&&(a.af.zz=!0,a.af.FS(0),a.af.Va(b),a.af.FS(c),a.af.zz=!1,a.C$(null))}gvjs_.yf=function(){return this.af.yf()};gvjs_.Fw=function(a){this.af.Fw(a)};gvjs_.xf=function(){return this.af.xf()};gvjs_.ku=function(a){this.af.ku(a)};
function gvjs_$O(a,b){return b<=a.af.getValue()+a.af.am()/2?a.Pd:a.gj}gvjs_.C$=function(){gvjs_4O(this);gvjs_2O(this);this.dispatchEvent(gvjs_Jq)};
function gvjs_4O(a){if(a.Pd&&!a.GP){var b=gvjs_eP(a,gvjs_bP(a,a.Pd)),c=gvjs_eP(a,gvjs_bP(a,a.gj));if(a.rb==gvjs_1)a.Pd.style.top=b.y+gvjs__,a.gj.style.top=c.y+gvjs__,a.Hg&&(b=gvjs_fP(c.y,b.y,a.Pd.offsetHeight),a.Hg.style.top=b.offset+gvjs__,a.Hg.style.height=b.size+gvjs__);else{var d=a.Vl&&a.wh()?gvjs_y:gvjs_zg;a.Pd.style[d]=b.x+gvjs__;a.gj.style[d]=c.x+gvjs__;a.Hg&&(b=gvjs_fP(b.x,c.x,a.Pd.offsetWidth),a.Hg.style[d]=b.offset+gvjs__,a.Hg.style.width=b.size+gvjs__)}}}
function gvjs_fP(a,b,c){var d=Math.ceil(c/2);return{offset:a+d,size:Math.max(b-a+c-2*d,0)}}function gvjs_eP(a,b){var c=new gvjs_C;if(a.Pd){var d=a.yf(),e=a.xf();b=b==d&&d==e?0:(b-d)/(e-d);a.rb==gvjs_1?(d=a.Pd.offsetHeight,d=a.j().clientHeight-d,b=Math.round(b*d),c.x=a.h0?0:gvjs_aP(a,a.Pd),c.y=d-b):(d=a.j().clientWidth-a.Pd.offsetWidth,c.x=Math.round(b*d),c.y=a.h0?0:a.Pd.offsetTop)}return c}
function gvjs_7O(a,b){b=gvjs_Ec(b,a.yf(),a.xf());a.GP&&(a.YG.stop(!0),a.YG.na());var c=new gvjs_UO,d=gvjs_$O(a,b),e=a.getValue(),f=a.am(),g=gvjs_bP(a,d),h=gvjs_eP(a,g);var k=a.XH();Math.abs(b-g)<k&&(b=gvjs_Ec(g+(b>g?k:-k),a.yf(),a.xf()));gvjs_6O(a,d,b);g=gvjs_eP(a,gvjs_bP(a,d));k=a.rb==gvjs_1?[gvjs_aP(a,d),g.y]:[g.x,d.offsetTop];h=new gvjs_WO(d,[h.x,h.y],k,100);h.yq(a.Vl);c.add(h);a.Hg&&gvjs_Ria(a,d,e,f,g,c);a.J5&&(b=a.J5.oCa(e,b,100),gvjs_m(b,function(l){c.add(l)}));a.YG=c;a.kc().D(c,gvjs_Y,a.tna);
a.GP=!0;c.play(!1)}
function gvjs_Ria(a,b,c,d,e,f){var g=gvjs_eP(a,c),h=gvjs_eP(a,c+d);c=g;d=h;b==a.Pd?c=e:d=e;a.rb==gvjs_1?(b=gvjs_fP(h.y,g.y,a.Pd.offsetHeight),g=gvjs_fP(d.y,c.y,a.Pd.offsetHeight),e=new gvjs_WO(a.Hg,[gvjs_aP(a,a.Hg),b.offset],[gvjs_aP(a,a.Hg),g.offset],100),b=new gvjs_YO(a.Hg,b.size,g.size,100),e.yq(a.Vl),b.yq(a.Vl),f.add(e),f.add(b)):(b=gvjs_fP(g.x,h.x,a.Pd.offsetWidth),g=gvjs_fP(c.x,d.x,a.Pd.offsetWidth),e=new gvjs_WO(a.Hg,[b.offset,a.Hg.offsetTop],[g.offset,a.Hg.offsetTop],100),b=new gvjs_XO(a.Hg,
b.size,g.size,100),e.yq(a.Vl),b.yq(a.Vl),f.add(e),f.add(b))}gvjs_.tna=function(){this.GP=!1;this.dispatchEvent("g")};gvjs_.setOrientation=function(a){if(this.rb!=a){var b=this.ra(this.rb),c=this.ra(a);this.rb=a;this.j()&&(a=this.j(),gvjs_xB(a,b)&&(gvjs_AB(a,b),gvjs_yB(a,c)),b=this.Vl&&this.wh()?gvjs_y:gvjs_zg,this.Pd.style[b]=this.Pd.style.top="",this.gj.style[b]=this.gj.style.top="",this.Hg&&(this.Hg.style[b]=this.Hg.style.top="",this.Hg.style.width=this.Hg.style.height=""),gvjs_4O(this))}};
gvjs_.zi=function(){return this.rb};gvjs_.O=function(){gvjs_0O.o.O.call(this);this.Qv&&this.Qv.na();delete this.Qv;this.YG&&this.YG.na();delete this.YG;delete this.Pd;delete this.gj;this.Hg&&delete this.Hg;this.af.na();delete this.af;this.Vf&&(this.Vf.na(),delete this.Vf);this.In&&(this.In.na(),delete this.In);this.Mm&&(this.Mm.na(),delete this.Mm);this.zq&&(this.zq.na(),delete this.zq)};gvjs_.LA=1;gvjs_.XH=function(){return this.af.XH()};gvjs_.SS=function(a){this.af.SS(a)};gvjs_.getValue=function(){return this.af.getValue()};
gvjs_.Va=function(a){gvjs_6O(this,this.Pd,a)};gvjs_.am=function(){return this.af.am()};gvjs_.FS=function(a){gvjs_6O(this,this.gj,this.af.getValue()+a)};gvjs_.setVisible=function(a){gvjs_4(this.j(),a);a&&gvjs_4O(this)};function gvjs_2O(a){var b=a.j();b&&(gvjs_nA(b,"valuemin",a.yf()),gvjs_nA(b,"valuemax",a.xf()),gvjs_nA(b,"valuenow",a.getValue()),gvjs_nA(b,"valuetext",a.tsa(a.getValue())||""))}
function gvjs_5O(a,b){b?(a.In||(a.In=new gvjs_wD(a.j())),a.kc().D(a.In,gvjs_Rt,a.y$,{passive:!1})):a.kc().zb(a.In,gvjs_Rt,a.y$,{passive:!1})}gvjs_.Gb=function(a){this.yg!=a&&this.dispatchEvent(a?gvjs_Mr:gvjs_Er)&&(this.yg=a,gvjs_3O(this,a),a||this.y3(),gvjs_CB(this.j(),"goog-slider-disabled",!a))};gvjs_.isEnabled=function(){return this.yg};function gvjs_aP(a,b){return a.Vl?gvjs_Az(b):b.offsetLeft}var gvjs_Sia={YL:gvjs_1,TL:gvjs_Z};function gvjs_gP(a,b){this.B4=a;this.pf=b}
gvjs_gP.prototype.getUrl=function(){return this.B4};gvjs_gP.prototype.md=function(a){return this.pf[a].id};gvjs_gP.prototype.Y=function(a){return this.pf[a].type};gvjs_gP.prototype.Z=function(){return this.pf.length};function gvjs_Tia(a,b){var c=new gvjs_cm(a);c.ql("limit 1");c.send(function(d){if(d.hk())b(null);else{var e=[];d=d.Wa();for(var f=0;f<d.Z();f++)e.push({id:d.md(f),type:d.Y(f)});b(new gvjs_gP(a,e))}})};function gvjs_hP(a,b){this.Wh=[];this.V=a;this.$da=b||null;this.$aa=(this.$da||this.V.Wa()).Y(0)==gvjs_Pa?"second":gvjs_Oa}var gvjs_iP=["year",gvjs_KO,"day","hour","minute","second"],gvjs_jP=[function(a){return a.getFullYear()},function(a){return a.getMonth()+1},function(a){return a.getDate()},function(a){return a.getHours()},function(a){return a.getMinutes()},function(a){return a.getSeconds()}],gvjs_Uia=[gvjs_qa,gvjs_la,gvjs_sa,gvjs_ga,gvjs_ta,"June","July",gvjs_ha,gvjs_Ba,gvjs_xa,gvjs_va,gvjs_ja];
function gvjs_Via(a,b){function c(e){b(new gvjs_hP(a,e))}if(a.Wa())c(null);else{var d=a.Be;if(d)gvjs_Tia(d,c);else throw Error("Wrapper should hold dataTable or dataSourceUrl");}}function gvjs_Wia(a,b){var c=gvjs_Pn||gvjs_Pn;b=b||function(f){return f};for(var d=[],e=1;e<a.Z();e++)d.push({column:e,aggregation:c,type:a.Y(e),label:a.Ca(e),id:a.md(e)});return gvjs_Sn(a,[{column:0,modifier:b,type:gvjs_c,label:a.Ca(0),id:a.md(0)}],d)}
gvjs_hP.prototype.XF=function(){var a=this.V.bo();a=new gvjs_R(a);var b=a.Wa();if(null!=b){for(var c=this.Wh,d=0;d<b.aa();d++){a:{var e=this.Wh;for(var f=b.getValue(d,0),g=0;g<e.length;g++){var h=e[g];gvjs_iP[g]==gvjs_KO&&h++;if(gvjs_jP[g](f)!=h){e=!1;break a}}e=!0}e||(b.Xz(d),d--)}b=gvjs_Wia(b,gvjs_jP[c.length]);a.eh(b)}else{b=this.$da;b.Y(0)==gvjs_Oa&&(this.$aa="day");c="select "+gvjs_kP(this)+"("+b.md(0)+")";gvjs_kP(this)==gvjs_KO&&(c+=" + 1");for(d=1;d<b.Z();d++)c+=", sum("+b.md(d)+")";b=[c,gvjs_Xia(this,
b),"group by "+gvjs_kP(this)+"("+b.md(0)+")",gvjs_Yia(this,b)].join(" ");a.ql(b)}return a};gvjs_hP.prototype.WN=function(a){var b=gvjs_kP(this);if(b==this.$aa)return!1;b==gvjs_KO&&a--;this.Wh.push(a);return!0};gvjs_hP.prototype.rollup=function(){return 0<this.Wh.length?(this.Wh.pop(),!0):!1};function gvjs_kP(a){return gvjs_iP[a.Wh.length]}
function gvjs_Zia(a){var b=[];0<a.Wh.length&&b.push(String(a.Wh[0]));if(1<a.Wh.length){var c=a.Wh[1];c=gvjs_Uia[c];b.push(String(c))}2<a.Wh.length&&b.push(String(a.Wh[2]));3<a.Wh.length&&(c=a.Wh[3],a=a.Wh[4]||"00",a=String(a),1==a.length&&(a="0"+a),b.push(c+":"+a));return b.join(" ")}function gvjs_Xia(a,b){if(0==a.Wh.length)return"";for(var c=[],d=0;d<a.Wh.length;d++)c.push(gvjs_iP[d]+"("+b.md(0)+") = "+a.Wh[d]);return"where "+c.join(gvjs_Vn)}
function gvjs_Yia(a,b){b="order by "+gvjs_kP(a)+"("+b.md(0)+")";gvjs_kP(a)==gvjs_KO&&(b+=" + 1");return b};function gvjs_lP(a){this.ha=a}gvjs_=gvjs_lP.prototype;gvjs_.bn=null;gvjs_.V=null;gvjs_.draw=function(a){var b=this;gvjs_Via(a,function(c){b.bn=c;b.NA()})};gvjs_.rollup=function(){null!=this.bn&&null!=this.V&&this.bn.rollup()&&this.NA()};gvjs_.WN=function(a){(a=this.bn.WN(a))&&this.NA();return a};gvjs_.Jqa=function(){var a=this.V.vf().getSelection()[0].row;a=this.V.NO().Wa().getValue(a,0);this.WN(a)};
gvjs_.NA=function(){this.V&&gvjs_3k(this.V);var a=this.V=this.bn.XF(),b=this.V,c=b.getOption(gvjs_Gs)||{};c.title=gvjs_kP(this.bn);b.$(gvjs_Gs,c);b.$(gvjs_Iv,gvjs_Zia(this.bn));a.$(gvjs_tg,!0);b=gvjs_k(this.Jqa,this);gvjs_Xk(a,gvjs_z,b);a.draw(this.ha)};function gvjs_mP(a){gvjs_SO.call(this,a)}gvjs_l(gvjs_mP,gvjs_SO);gvjs_mP.prototype.XF=function(){return this.apply()};gvjs_mP.prototype.apply=function(){if(!this.Wa())throw Error(gvjs_BO);return this.a6(this.Wa(),this.cd(),this.getState())};gvjs_mP.prototype.a6=function(a){return a};function gvjs_nP(a){gvjs_SO.call(this,a)}gvjs_l(gvjs_nP,gvjs_mP);gvjs_nP.prototype.bn=null;gvjs_nP.prototype.a6=function(a,b,c){a=c.targetValue;"drilldown"==c.action?typeof a===gvjs_c&&this.bn.WN(a):this.bn.rollup();c=this.bn.XF().Wa();if(null==c)throw"Operator could not be applied to null data table.";return c};gvjs_nP.prototype.gt=function(){return"DrilldownOperatorUi"};gvjs_nP.prototype.pr=function(a){this.clear();this.bn=new gvjs_hP(new gvjs_R({Lb:a}))};
function gvjs_oP(a){gvjs_RO.call(this,a)}gvjs_l(gvjs_oP,gvjs_RO);gvjs_oP.prototype.Sf=null;gvjs_oP.prototype.getState=function(){if(!this.Sf)return{};var a=this.Sf?this.Sf.value:"{}";try{a=gvjs_gc(a)}catch(b){}return a=gvjs_i(a)?a:{}};gvjs_oP.prototype.draw=function(a){this.Sf=this.rW(a);this.getContainer().appendChild(this.Sf)};
gvjs_oP.prototype.rW=function(a){var b=this,c=gvjs_F(gvjs_oa);c.setAttribute(gvjs_ug,gvjs_nh(this.getContainer())+"-input");a&&(c.value=gvjs_hc(a));this.addEventListener(c,gvjs_pq,function(){gvjs_M(b,gvjs_MO,null)},!1);return c};function gvjs_pP(a){gvjs_SO.call(this,a);this.US=[]}gvjs_l(gvjs_pP,gvjs_SO);gvjs_pP.prototype.pr=function(){this.clear();this.US=this.cd().ea("setters")||[]};gvjs_pP.prototype.apply=function(){return this.XU(this.Wa(),this.cd(),this.getState())};gvjs_pP.prototype.XU=function(a,b,c){gvjs_m(this.BO(),function(d){gvjs_m(this.US,function(e){d.setProperty(e.output,c[e.input])},this)},this);return a};function gvjs_qP(a){gvjs_pP.call(this,a)}gvjs_l(gvjs_qP,gvjs_pP);gvjs_=gvjs_qP.prototype;gvjs_.Xa=null;gvjs_.Bb=null;gvjs_.em=function(a,b){a=gvjs_qP.o.em.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Bb;null==a.label&&(a.label="");return a};gvjs_.pr=function(a,b,c){this.Xa=gvjs_t(b,gvjs_Dg);this.Bb=gvjs_t(b,gvjs_Cg);this.US=[{input:"lowValue",og:gvjs_r(b,"lowKey")},{input:"highValue",og:gvjs_r(b,"highKey")}];this.HL(c)};
gvjs_.HL=function(a){if(a.lowThumbAtMinimum)a.lowValue=this.Xa;else{var b=gvjs_fc(String(a.lowValue));isNaN(b)&&(b=Number.NEGATIVE_INFINITY);a.lowValue=gvjs_Ec(b,this.Xa,this.Bb)}a.highThumbAtMaximum?a.highValue=this.Bb:(b=gvjs_fc(String(a.highValue)),isNaN(b)&&(b=Number.POSITIVE_INFINITY),a.highValue=gvjs_Ec(b,this.Xa,this.Bb))};function gvjs_rP(a){gvjs_SO.call(this,a)}gvjs_l(gvjs_rP,gvjs_SO);gvjs_rP.prototype.hB=function(){return this.apply()};gvjs_rP.prototype.apply=function(){if(!this.Wa())throw Error(gvjs_BO);return this.WF(this.Wa(),this.cd(),this.getState())};gvjs_rP.prototype.WF=function(a){return new gvjs_Q(a)};function gvjs_sP(a){gvjs_SO.call(this,a);this.Fe=-1}gvjs_l(gvjs_sP,gvjs_rP);gvjs_=gvjs_sP.prototype;gvjs_.Bq=null;gvjs_.Xa=null;gvjs_.Bb=null;gvjs_.NS=function(a){this.Xa=a};gvjs_.MS=function(a){this.Bb=a};function gvjs_tP(a,b){if(b.lowThumbAtMinimum)b.lowValue=a.Xa;else{var c=a.M4(b.lowValue);isNaN(c)&&(c=Number.NEGATIVE_INFINITY);b.lowValue=gvjs_Ec(c,a.Xa,a.Bb)}b.highThumbAtMaximum?b.highValue=a.Bb:(c=a.M4(b.highValue),isNaN(c)&&(c=Number.POSITIVE_INFINITY),b.highValue=gvjs_Ec(c,a.Xa,a.Bb))}
gvjs_.WF=function(a,b,c){a=new gvjs_Q(a);b={column:this.Fe,test:this.oY(b,c.lowValue.valueOf(),c.highValue.valueOf())};a.Dp(a.ht([b]));return a};gvjs_.oY=function(a,b,c){return function(d){return b<=d&&c>=d}};function gvjs_uP(a){gvjs_0O.call(this,a)}gvjs_l(gvjs_uP,gvjs_0O);gvjs_uP.prototype.XB=null;gvjs_uP.prototype.ra=function(a){return a==gvjs_1?"google-visualization-controls-slider-vertical":"google-visualization-controls-slider-horizontal"};gvjs_uP.prototype.Ob=function(){gvjs_uP.o.Ob.call(this);this.kc().D(this,gvjs_Jq,gvjs_k(this.Ega,this));this.Ega()};
gvjs_uP.prototype.Ega=function(){var a=gvjs_PO(this.Pd),b=gvjs_PO(this.gj);this.zi()==gvjs_1?(this.XB.style.height=gvjs_Ny(Math.abs(b.y-a.y),!0),this.XB.style.top=Math.min(b.y,a.y)+gvjs__):(gvjs_Xy(this.XB,Math.abs(b.x-a.x)),this.XB.style.left=Math.min(b.x,a.x)+gvjs__)};function gvjs_1O(a){a=a.xa().J(gvjs_v,"google-visualization-controls-slider-thumb");gvjs_mA(a,gvjs_Aq);return a};function gvjs_vP(a){gvjs_RO.call(this,a);this.Xp=this.Hm=0}gvjs_l(gvjs_vP,gvjs_RO);gvjs_=gvjs_vP.prototype;gvjs_.O=function(){gvjs_K(this.Hm);gvjs_K(this.Mc);gvjs_vP.o.O.call(this)};gvjs_.dw=null;gvjs_.Nv=null;gvjs_.Mc=null;gvjs_.getState=function(){if(!this.Mc)return{lowValue:null,highValue:null,lowThumbAtMinimum:null,highThumbAtMaxium:null};var a=this.Mc.getValue(),b=this.Mc.am();return{lowValue:a+this.Xp,highValue:a+b+this.Xp,lowThumbAtMinimum:a===this.Mc.yf(),highThumbAtMaximum:a+b===this.Mc.xf()}};
function gvjs_wP(){return gvjs_F(gvjs_7e,{"class":"google-visualization-controls-rangefilter-thumblabel"},"-")}gvjs_.rxa=function(){this.z4();this.Hm&&gvjs_2l(this.Hm);this.Hm=gvjs_1l(function(){this.Hm=0;gvjs_M(this,gvjs_MO,null)},200,this)};
function gvjs_xP(a,b,c,d,e){var f=gvjs_s(d,"showRangeValues");e=gvjs_r(d,gvjs_7t,e.orientation,gvjs_Sia);var g=new gvjs_pB;b.Ia(g,!0);gvjs_yB(g.j(),gvjs_T);f&&(e===gvjs_Z?(a.dw=gvjs_wP(),g.ib().appendChild(a.dw)):(a.Nv=gvjs_wP(),g.ib().appendChild(a.Nv)));b=new gvjs_uP;gvjs_K(a.Mc);a.Mc=b;a.dfa(d);b=a.uY(d,gvjs_Dg);var h=a.uY(d,gvjs_Cg);if(null==b||null==h)throw Error("minValue and maxValue must be specified");c=a.Bda(b,h,c);b=c.minValue;h=c.maxValue;c=c.state;a.Xp=b;h-=a.Xp;c.lowValue-=a.Xp;c.highValue-=
a.Xp;a.Mc.Fw(0);a.Mc.ku(h);a.Mc.setOrientation(e);b=c.lowThumbAtMinimum?a.Mc.yf():c.lowValue;gvjs_dP(a.Mc,b,c.highThumbAtMaximum?a.Mc.xf():c.highValue-b);g.Ia(a.Mc,!0);f&&(e==gvjs_Z?(a.Nv=gvjs_wP(),g.ib().appendChild(a.Nv)):(a.dw=gvjs_wP(),g.ib().appendChild(a.dw)),a.h1&&a.h1(d),a.z4());a.addEventListener(a.Mc,gvjs_Jq,a.rxa,!1,a)};function gvjs_yP(a,b){var c=b.ea("filterColumnIndex");if(null!=c)return b=parseInt(c,10),a.md(b),b;if(b=gvjs_r(b,"filterColumnLabel")){a:{c=a.Z();for(var d=0;d<c;d++)if(a.Ca(d)==b)break a;throw Error("Invalid column label:"+b);}return d}throw Error("Either filterColumnIndex or filterColumnLabel must be specified.");};function gvjs_zP(a){gvjs_SO.call(this,a);this.Fe=-1}gvjs_l(gvjs_zP,gvjs_rP);gvjs_=gvjs_zP.prototype;gvjs_.Bq=null;gvjs_.vc=null;gvjs_.Of=function(){return{useFormattedValue:!1,values:null}};gvjs_.em=function(a,b){a=gvjs_zP.o.em.call(this,a,b);null==a.label&&(a.label=this.Bq);a.values=this.vc;return a};
gvjs_.pr=function(a,b,c){this.clear();this.Fe=gvjs_yP(a,b);this.Bq=a.Ca(this.Fe);var d=b.ea("values");if(gvjs_Nh(d)&&d.length)this.vc=d;else{b=gvjs_s(b,gvjs_NO);d=new gvjs_E;for(var e=[],f=0;f<a.aa();f++){var g=b?a.Ga(f,this.Fe):a.getValue(f,this.Fe);null==g||d.contains(g)||(d.add(g),e.push(g))}this.vc=e}this.HL(c)};
gvjs_.HL=function(a){var b=a.selectedValues;if(b){if(!gvjs_Nh(b))throw Error(gvjs_AO);var c=new gvjs_E;gvjs_m(this.vc,function(d){null!=d&&c.add(String(d))});a.selectedValues=gvjs_zb(b,function(d){return c.contains(String(d))})}};
gvjs_.WF=function(a,b,c){var d=new gvjs_E;c=c.selectedValues;if(gvjs_Nh(c))for(var e=0;e<c.length;e++)null!=c[e]&&d.add(String(c[e]));if(0==d.tb())return new gvjs_Q(a);c=gvjs_s(b,gvjs_NO);b=[];for(e=0;e<a.aa();e++){if(c)var f=a.Ga(e,this.Fe);else f=a.getValue(e,this.Fe),null!=f&&(f=String(f));d.contains(f)&&b.push(e)}a=new gvjs_Q(a);a.Dp(b);return a};function gvjs_AP(a,b,c,d){gvjs_pB.call(this,d);this.Tb=a;this.isa=b==gvjs_1;this.hwa=c||""}gvjs_l(gvjs_AP,gvjs_pB);gvjs_=gvjs_AP.prototype;gvjs_.Uaa=null;gvjs_.KG=null;function gvjs_BP(a){if(!a.label)return null;var b=a.labelStacking==gvjs_1?gvjs_1:gvjs_Z,c;a.labelSeparator&&(c=String(a.labelSeparator));return new gvjs_AP(String(a.label),b,c)}
gvjs_.J=function(){var a=this.G.J(gvjs_v);this.H=a;this.Uaa=gvjs_F("LABEL","google-visualization-controls-label",this.Tb+this.hwa);a.appendChild(this.Uaa);this.KG=gvjs_F(gvjs_v);this.isa||gvjs_yB(this.KG,gvjs_T);a.appendChild(this.KG)};gvjs_.Qh=function(){return!1};gvjs_.ib=function(){return this.KG};gvjs_.addElement=function(a){this.KG.appendChild(a)};function gvjs_CP(a,b){this.de=a;this.Rba=b}gvjs_CP.prototype.Fd=function(){return this.Rba.Fd(this)};gvjs_CP.prototype.getId=function(){return this.Rba.getId(this)};gvjs_CP.prototype.get=function(){return this.de};function gvjs__ia(a,b){return a.Fd().localeCompare(b.Fd())}function gvjs_DP(){}gvjs_DP.prototype.Fd=function(a){return String(a.get())};gvjs_DP.prototype.getId=function(a){return String(a.get())};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function gvjs_EP(a){gvjs_Vk.call(this);this.Tc=null;this.H=a;a=gvjs_q||gvjs_mc||gvjs_oc&&!gvjs_zc("531")&&a.tagName==gvjs_qp;this.ba=new gvjs_hz(this);this.ba.D(this.H,a?[gvjs_$s,"paste","cut","drop",gvjs_2s]:gvjs_2s,this)}gvjs_l(gvjs_EP,gvjs_Vk);
gvjs_EP.prototype.handleEvent=function(a){if(a.type==gvjs_2s)gvjs_q&&gvjs_zc(10)&&0==a.keyCode&&0==a.charCode||(gvjs_FP(this),this.dispatchEvent(gvjs_GP(a)));else if(a.type!=gvjs_$s||gvjs_Qia(a)){var b=a.type==gvjs_$s?this.H.value:null;gvjs_q&&229==a.keyCode&&(b=null);var c=gvjs_GP(a);gvjs_FP(this);this.Tc=gvjs_1l(function(){this.Tc=null;this.H.value!=b&&this.dispatchEvent(c)},0,this)}};function gvjs_FP(a){null!=a.Tc&&(gvjs_2l(a.Tc),a.Tc=null)}
function gvjs_GP(a){a=new gvjs_Ak(a.wi);a.type=gvjs_2s;return a}gvjs_EP.prototype.O=function(){gvjs_EP.o.O.call(this);this.ba.na();gvjs_FP(this);delete this.H};function gvjs_HP(a,b,c){gvjs_vk.call(this,a,b);this.item=c}gvjs_l(gvjs_HP,gvjs_vk);function gvjs_IP(a,b){gvjs_pB.call(this,b);this.Tb=a||""}var gvjs_JP;gvjs_l(gvjs_IP,gvjs_pB);gvjs_=gvjs_IP.prototype;gvjs_.Aq=null;gvjs_.vsa=10;function gvjs_KP(){null==gvjs_JP&&(gvjs_JP=gvjs_LO in gvjs_Li(gvjs_oa));return gvjs_JP}gvjs_.FC=!1;gvjs_.J=function(){this.H=this.xa().J(gvjs_oa,{type:gvjs_A})};
gvjs_.Lf=function(a){gvjs_IP.o.Lf.call(this,a);this.Tb||(this.Tb=a.getAttribute(gvjs_xg)||"");gvjs_pw(gvjs_Hc(a))==a&&(this.FC=!0,a=this.j(),gvjs_AB(a,this.XI));gvjs_KP()&&(this.j().placeholder=this.Tb);a=this.j();gvjs_nA(a,gvjs_xg,this.Tb)};
gvjs_.Ob=function(){gvjs_IP.o.Ob.call(this);var a=new gvjs_hz(this);a.D(this.j(),gvjs_8r,this.t$);a.D(this.j(),gvjs_pq,this.YO);if(gvjs_KP())this.ba=a;else{gvjs_nc&&a.D(this.j(),[gvjs_wg,gvjs_$s,gvjs_at],this.Ppa);var b=gvjs_Hc(this.j());a.D(gvjs_Cw(b),"load",this.Wqa);this.ba=a;gvjs_LP(this)}this.bq();this.j().sj=this};gvjs_.Ue=function(){gvjs_IP.o.Ue.call(this);this.ba&&(this.ba.na(),this.ba=null);this.j().sj=null};
function gvjs_LP(a){!a.aoa&&a.ba&&a.j().form&&(a.ba.D(a.j().form,"submit",a.Qpa),a.aoa=!0)}gvjs_.O=function(){gvjs_IP.o.O.call(this);this.ba&&(this.ba.na(),this.ba=null)};gvjs_.XI="label-input-label";gvjs_.t$=function(){this.FC=!0;var a=this.j();gvjs_AB(a,this.XI);if(!gvjs_KP()&&!gvjs_MP(this)&&!this.wra){var b=this;a=function(){b.j()&&(b.j().value="")};gvjs_q?gvjs_1l(a,10):a()}};gvjs_.YO=function(){gvjs_KP()||(this.ba.zb(this.j(),gvjs_0q,this.t$),this.Aq=null);this.FC=!1;this.bq()};
gvjs_.Ppa=function(a){27==a.keyCode&&(a.type==gvjs_$s?this.Aq=this.j().value:a.type==gvjs_wg?this.j().value=this.Aq:a.type==gvjs_at&&(this.Aq=null),a.preventDefault())};gvjs_.Qpa=function(){gvjs_MP(this)||(this.j().value="",gvjs_1l(this.apa,10,this))};gvjs_.apa=function(){gvjs_MP(this)||(this.j().value=this.Tb)};gvjs_.Wqa=function(){this.bq()};gvjs_.hasFocus=function(){return this.FC};function gvjs_MP(a){return!!a.j()&&""!=a.j().value&&a.j().value!=a.Tb}
gvjs_.clear=function(){this.j().value="";null!=this.Aq&&(this.Aq="")};gvjs_.reset=function(){gvjs_MP(this)&&(this.clear(),this.bq())};gvjs_.Va=function(a){null!=this.Aq&&(this.Aq=a);this.j().value=a;this.bq()};gvjs_.getValue=function(){return null!=this.Aq?this.Aq:gvjs_MP(this)?this.j().value:""};gvjs_.Xn=function(a){var b=this.j();gvjs_KP()?(b&&(b.placeholder=a),this.Tb=a):gvjs_MP(this)||(b&&(b.value=""),this.Tb=a,this.mea());b&&gvjs_nA(b,gvjs_xg,this.Tb)};gvjs_.Fd=function(){return this.Tb};
gvjs_.bq=function(){var a=this.j();gvjs_KP()?this.j().placeholder!=this.Tb&&(this.j().placeholder=this.Tb):gvjs_LP(this);gvjs_nA(a,gvjs_xg,this.Tb);gvjs_MP(this)?(a=this.j(),gvjs_AB(a,this.XI)):(this.wra||this.FC||(a=this.j(),gvjs_yB(a,this.XI)),gvjs_KP()||gvjs_1l(this.mea,this.vsa,this))};gvjs_.Gb=function(a){this.j().disabled=!a;var b=this.j();gvjs_CB(b,this.XI+gvjs_po,!a)};gvjs_.isEnabled=function(){return!this.j().disabled};
gvjs_.mea=function(){!this.j()||gvjs_MP(this)||this.FC||(this.j().value=this.Tb)};function gvjs_NP(a,b,c){gvjs_pB.call(this,a);this.sj=c||new gvjs_IP;this.yg=!0;a=this.ka=b||new gvjs_ZC(this.xa());a.setVisible(!1);a.PF=!1;a.P5=!0}gvjs_l(gvjs_NP,gvjs_pB);gvjs_=gvjs_NP.prototype;gvjs_.Ec=null;gvjs_.eD=null;gvjs_.sj=null;gvjs_.ka=null;gvjs_.UA=-1;gvjs_.Sf=null;gvjs_.F_=gvjs_Pb;gvjs_.wB=null;gvjs_.TW="";gvjs_.Pna="";gvjs_.qq=null;gvjs_.Jga=!1;
gvjs_.J=function(){this.Sf=this.xa().J(gvjs_oa,{name:this.Pna,type:gvjs_A,autocomplete:"off"});this.wB=this.xa().J(gvjs_7e,"goog-combobox-button");this.H=this.xa().J(gvjs_7e,"goog-combobox",this.Sf,this.wB);this.Jga&&(gvjs_0c(this.wB,"\u25bc"),gvjs_2y(this.wB,!0));this.Sf.setAttribute(gvjs_xg,this.TW);this.sj.cb(this.Sf);this.ka.xp(!1);this.ka.Ab||this.Ia(this.ka,!0)};
gvjs_.Gb=function(a){this.yg=a;this.sj.Gb(a);gvjs_CB(this.j(),"goog-combobox-disabled",!a)};gvjs_.isEnabled=function(){return this.yg};gvjs_.Ob=function(){gvjs_NP.o.Ob.call(this);var a=this.kc();a.D(this.j(),gvjs_Fg,this.fua);a.D(this.xa().jc(),gvjs_Fg,this.gua);a.D(this.Sf,gvjs_pq,this.nua);this.Vf=new gvjs_7B(this.Sf);a.D(this.Vf,gvjs_9s,this.nj);this.Ec=new gvjs_EP(this.Sf);a.D(this.Ec,gvjs_2s,this.oua);a.D(this.ka,gvjs_Pp,this.qua)};
gvjs_.Ue=function(){this.Vf.na();delete this.Vf;this.Ec.na();this.Ec=null;gvjs_NP.o.Ue.call(this)};gvjs_.Qh=function(){return!1};gvjs_.O=function(){gvjs_NP.o.O.call(this);this.VM();this.sj.na();this.ka.na();this.wB=this.Sf=this.ka=this.sj=null};gvjs_.QB=function(){this.VM();gvjs_OP(this);this.ka.fh(-1)};gvjs_.Mj=function(a){this.ka.Ia(a,!0);this.UA=-1};gvjs_.Du=function(a,b){this.ka.nx(a,b,!0);this.UA=-1};gvjs_.removeItem=function(a){if(a=this.ka.removeChild(a,!0))a.na(),this.UA=-1};gvjs_.td=function(a){return this.ka.hf(a)};
gvjs_.th=function(){return this.ka.Ge()};gvjs_.Vd=function(){return this.ka};gvjs_.Va=function(a){this.sj.getValue()!=a&&(this.sj.Va(a),this.ZO())};gvjs_.getValue=function(){return this.sj.getValue()};function gvjs_PP(a,b){var c=a.ka.isVisible(),d;if(-1==a.UA){for(var e=d=0,f=a.ka.Ge();e<f;e++)a.ka.hf(e).isVisible()&&d++;a.UA=d}d=a.UA;c&&0==d?gvjs_OP(a):!c&&0<d&&(b&&(a.GK(""),a.JS(gvjs_Sb(a.sj.getValue().toLowerCase()))),gvjs_1l(a.VM,1,a),a.ka.setVisible(!0),gvjs_yB(a.j(),gvjs_DO));a.uR()}
gvjs_.uR=function(){this.ka&&this.ka.isVisible()&&(new gvjs_FC(this.j(),9,!0)).$f(this.ka.j(),8)};function gvjs_OP(a){a.ka.setVisible(!1);gvjs_AB(a.j(),gvjs_DO)}gvjs_.VM=function(){this.qq&&(gvjs_2l(this.qq),this.qq=null)};gvjs_.fua=function(a){this.yg&&(a.target==this.j()||a.target==this.Sf||gvjs_Zc(this.wB,a.target))&&(this.ka.isVisible()?this.QB():(gvjs_PP(this,!0),gvjs_lc&&this.Sf.focus(),this.Sf.select(),this.ka.er=!0,a.preventDefault()));a.stopPropagation()};
gvjs_.gua=function(a){gvjs_Zc(this.ka.j(),a.target)||this.QB()};gvjs_.qua=function(a){var b=a.target;this.dispatchEvent(new gvjs_HP(gvjs_Pp,this,b))&&(b=b.hj(),this.sj.getValue()!=b&&(this.sj.Va(b),this.dispatchEvent(gvjs_Jq)),this.QB());a.stopPropagation()};gvjs_.nua=function(){this.VM();this.qq=gvjs_1l(this.QB,250,this)};
gvjs_.nj=function(a){var b=this.ka.isVisible();if(b&&this.ka.nj(a))return!0;var c=!1;switch(a.keyCode){case 27:b&&(this.QB(),c=!0);break;case 9:b&&(b=gvjs_PC(this.ka))&&(b.ei(a),c=!0);break;case 38:case 40:b||(gvjs_PP(this,!0),c=!0)}c&&a.preventDefault();return c};gvjs_.oua=function(){this.ZO()};gvjs_.ZO=function(){var a=gvjs_Sb(this.sj.getValue().toLowerCase());this.GK(a);gvjs_pw(this.xa().jc())==this.Sf&&gvjs_PP(this,!1);var b=gvjs_PC(this.ka);""!=a&&b&&b.isVisible()||this.JS(a);this.eD=a;this.dispatchEvent(gvjs_Jq)};
gvjs_.GK=function(a){for(var b=!1,c=0,d=!this.F_(a,this.eD),e=0,f=this.ka.Ge();e<f;e++){var g=this.ka.hf(e);if(g instanceof gvjs_CC){if(!g.isVisible()&&!d)continue;var h=g.hj();h=typeof g.jsa==gvjs_a&&g.Paa||h&&this.F_(h.toLowerCase(),a);typeof g.GS==gvjs_a&&g.GS(a);g.setVisible(!!h);b=h||b}else b=g.isVisible()||b;g.isVisible()&&c++}this.UA=c};
gvjs_.JS=function(a){if(""!=a)for(var b=0,c=this.ka.Ge();b<c;b++){var d=this.ka.hf(b),e=d.hj();if(e&&this.F_(e.toLowerCase(),a)){this.ka.fh(b);d.GS&&d.GS(a);return}}this.ka.fh(-1)};function gvjs_QP(a,b,c,d){gvjs_CC.call(this,a,b,c,d)}gvjs_l(gvjs_QP,gvjs_CC);gvjs_kC("goog-combobox-item",function(){return new gvjs_QP(null)});gvjs_QP.prototype.Paa=!1;gvjs_QP.prototype.jsa=function(){return this.Paa};
gvjs_QP.prototype.GS=function(a){if(this.isEnabled()){var b=this.hj(),c=b.toLowerCase().indexOf(a);if(0<=c){var d=this.xa();this.setContent([d.createTextNode(b.substr(0,c)),d.J("B",null,b.substr(c,a.length)),d.createTextNode(b.substr(c+a.length))])}}};function gvjs_RP(){}gvjs_l(gvjs_RP,gvjs_GC);gvjs_Mh(gvjs_RP);gvjs_=gvjs_RP.prototype;gvjs_.J=function(a){var b=this.Zl(a);b=a.xa().J(gvjs_v,gvjs_Ep+b.join(" "),a.getContent());this.tl(b,a.yn());return b};gvjs_.Zk=function(){return gvjs_Aq};gvjs_.Qh=function(a){return a.tagName==gvjs_v};gvjs_.cb=function(a,b){gvjs_yB(b,gvjs_T);return gvjs_RP.o.cb.call(this,a,b)};gvjs_.getValue=function(){return""};gvjs_.ra=function(){return gvjs_EO};gvjs_kC(gvjs_EO,function(){return new gvjs_IC(null,gvjs_RP.lc())});function gvjs_SP(){}gvjs_l(gvjs_SP,gvjs_RP);gvjs_Mh(gvjs_SP);gvjs_SP.prototype.ra=function(){return gvjs_FO};gvjs_kC(gvjs_FO,function(){return new gvjs_IC(null,gvjs_SP.lc())});function gvjs_TP(a,b,c){gvjs_CC.call(this,a,b,c);this.D2(!0)}gvjs_l(gvjs_TP,gvjs_CC);gvjs_TP.prototype.ei=function(){return this.dispatchEvent(gvjs_Pp)};gvjs_kC(gvjs_Jp,function(){return new gvjs_TP(null)});function gvjs_UP(a){gvjs_RO.call(this,a);this.vc=[];this.Ig=new gvjs_xy}gvjs_l(gvjs_UP,gvjs_RO);gvjs_UP.prototype.m=null;gvjs_UP.prototype.jH=null;var gvjs_VP={qza:gvjs_GO,vza:gvjs_nq,xza:"belowWrapping",wza:gvjs_HO};gvjs_UP.prototype.O=function(){gvjs_K(this.jH);gvjs_UP.o.O.call(this)};gvjs_UP.prototype.getState=function(){for(var a={selectedValues:[]},b=this.Ig.Ka(),c=0;c<b.length;c++)a.selectedValues.push(b[c].get());return a};
gvjs_UP.prototype.draw=function(a,b){b=gvjs_p(b||{});b.caption||(b.caption="Choose a value...");b.valuesMediator=b.valuesMediator||new gvjs_DP;b.cssClass=b.cssClass?String(b.cssClass):"google-visualization-controls-categoryfilter";"allowMultiple"in b||(b.allowMultiple=!0);"allowNone"in b||(b.allowNone=!0);"allowTyping"in b||(b.allowTyping=!0);"sortValues"in b||(b.sortValues=!0);var c=!1,d;for(d in gvjs_VP)if(b.selectedValuesLayout==gvjs_VP[d]){c=!0;break}c||(b.selectedValuesLayout=gvjs_GO);this.m=
b;gvjs_0ia(this,a);(a=gvjs_BP(this.m))||(a=new gvjs_pB);a.W(this.getContainer());gvjs_yB(a.j(),this.m.cssClass);gvjs_K(this.jH);this.jH=this.m.allowTyping?this.m.allowMultiple?new gvjs_WP(this):new gvjs_XP(this):this.m.allowMultiple?new gvjs_YP(this):new gvjs_ZP(this);this.jH.W(a);this.Ig.isEmpty()||this.jH.rE()};
function gvjs_0ia(a,b){b=b||{};var c=a.m.valuesMediator,d=new gvjs_E;if(null!=b.selectedValues){if(!gvjs_Nh(b.selectedValues))throw Error(gvjs_AO);a.m.allowMultiple?gvjs_m(b.selectedValues,function(g){d.add((new gvjs_CP(g,c)).getId())}):b.selectedValues.length&&d.add((new gvjs_CP(b.selectedValues[0],c)).getId())}b=gvjs_Nh(a.m.values)?a.m.values:[];for(var e=0;e<b.length;e++){var f=new gvjs_CP(b[e],c);a.vc.push(f);d.contains(f.getId())&&a.Ig.set(f.getId(),f)}a.m.sortValues&&gvjs__h(a.vc,gvjs__ia);
!gvjs__P(a)&&0<a.vc.length&&0==a.Ig.tb()&&a.Ig.set(a.vc[0].getId(),a.vc[0])}gvjs_UP.prototype.xu=function(){gvjs_M(this,gvjs_MO,null)};function gvjs_0P(a){return a.Ig.tb()==a.vc.length}function gvjs__P(a){return!!a.m.allowNone}function gvjs_1P(a){gvjs_J.call(this);this.ec=a;this.Ke=null}gvjs_l(gvjs_1P,gvjs_J);gvjs_=gvjs_1P.prototype;gvjs_.O=function(){gvjs_K(this.Ke);gvjs_1P.o.O.call(this)};
gvjs_.W=function(a){gvjs_K(this.Ke);this.Ke=new gvjs_gD(this.ec.m.caption);this.wW();a.Ia(this.Ke,!0);this.ec.addEventListener(this.Ke,gvjs_Pp,this.Xo,!1,this);this.Ke.Gb(0<this.ec.vc.length)};gvjs_.wW=function(){for(var a=this.ec.vc,b=0;b<a.length;b++)this.Ke.Mj(new gvjs_TP(a[b].Fd(),a[b]))};gvjs_.rE=function(){};gvjs_.Xo=function(){this.ec.xu()};function gvjs_ZP(a){gvjs_1P.call(this,a)}gvjs_l(gvjs_ZP,gvjs_1P);
gvjs_ZP.prototype.wW=function(){var a=this.ec;gvjs__P(a)&&this.Ke.Mj(new gvjs_TP(a.m.caption));gvjs_ZP.o.wW.call(this)};gvjs_ZP.prototype.rE=function(){for(var a=this.ec.Ig.Ka()[0],b=0,c=this.Ke.th();b<c;b++)if(this.Ke.td(b).di==a){this.Ke.yk(b);break}};gvjs_ZP.prototype.Xo=function(a){this.ec.Ig.clear();var b=this.Ke.Ie().di;b&&this.ec.Ig.set(b.getId(),b);gvjs_ZP.o.Xo.call(this,a)};function gvjs_YP(a){gvjs_1P.call(this,a);this.wk=null}gvjs_l(gvjs_YP,gvjs_1P);gvjs_=gvjs_YP.prototype;
gvjs_.O=function(){gvjs_K(this.wk);gvjs_YP.o.O.call(this)};gvjs_.W=function(a){gvjs_YP.o.W.call(this,a);var b=this.ec.m.selectedValuesLayout;b==gvjs_GO&&this.Ke.ds(gvjs_T);gvjs_K(this.wk);this.wk=new gvjs_2P(b,gvjs_Zy(this.Ke.j()).width,gvjs__P(this.ec)?0:1);a.Ia(this.wk,!0);this.ec.addEventListener(this.wk,gvjs_Pp,this.iI,!1,this)};
gvjs_.rE=function(){for(var a=this.ec.Ig,b=0,c=this.Ke.th();b<c;b++)a.ze(this.Ke.td(b).di.getId())&&this.Ke.td(b).setVisible(!1);gvjs_3P(this.wk,a.Ka());this.Ke.rl(null);this.Ke.Gb(!gvjs_0P(this.ec))};gvjs_.Xo=function(a){var b=this.Ke.Ie().di;this.Ke.Ie().setVisible(!1);this.Ke.rl(null);this.ec.Ig.set(b.getId(),b);this.Ke.Gb(!gvjs_0P(this.ec));gvjs_3P(this.wk,this.ec.Ig.Ka());gvjs_YP.o.Xo.call(this,a)};
gvjs_.iI=function(a){(a=a.item)&&this.ec.Ig.remove(a.getId());this.Ke.Gb(!0);for(var b=0,c=this.Ke.th();b<c;b++)if(this.Ke.td(b).di==a){this.Ke.td(b).setVisible(!0);break}this.ec.xu()};function gvjs_4P(a){gvjs_J.call(this);this.ec=a;this.fe=null}gvjs_l(gvjs_4P,gvjs_J);gvjs_=gvjs_4P.prototype;gvjs_.O=function(){gvjs_K(this.fe);gvjs_4P.o.O.call(this)};
gvjs_.W=function(a){var b=this.ec.vc;gvjs_K(this.fe);this.fe=new gvjs_NP;this.fe.Jga=!0;var c=this.fe;c.TW=this.ec.m.caption;c.sj&&c.sj.Xn(c.TW);for(c=0;c<b.length;c++)this.fe.Mj(new gvjs_QP(b[c].Fd(),b[c]));a.Ia(this.fe,!0);this.fe.Gb(0<b.length);this.ec.addEventListener(this.fe,gvjs_Pp,this.Xo,!1,this);a=gvjs_zh(gvjs_ok(),gvjs_2s,null,this.fe.j())[0];this.ec.addEventListener(a,gvjs_pq,this.MY,!1,this)};gvjs_.rE=function(){};gvjs_.Xo=function(){this.ec.xu()};gvjs_.MY=function(){};
function gvjs_XP(a){gvjs_4P.call(this,a)}gvjs_l(gvjs_XP,gvjs_4P);gvjs_XP.prototype.rE=function(){this.fe.Va(this.ec.Ig.Ka()[0].Fd())};gvjs_XP.prototype.Xo=function(a){this.ec.Ig.clear();var b=a.item.getValue();b&&this.ec.Ig.set(b.getId(),b);gvjs_XP.o.Xo.call(this,a)};gvjs_XP.prototype.MY=function(){var a=this.ec.Ig;if(!this.fe.getValue()&&gvjs__P(this.ec)){var b=!a.isEmpty();a.clear();b&&this.ec.xu()}else a.isEmpty()?this.fe.Va(""):this.fe.Va(a.Ka()[0].Fd())};
function gvjs_WP(a){gvjs_4P.call(this,a);this.wk=null}gvjs_l(gvjs_WP,gvjs_4P);gvjs_=gvjs_WP.prototype;gvjs_.O=function(){gvjs_K(this.wk);gvjs_WP.o.O.call(this)};gvjs_.W=function(a){gvjs_WP.o.W.call(this,a);var b=this.ec.m.selectedValuesLayout;b==gvjs_GO&&gvjs_yB(this.fe.j(),gvjs_T);gvjs_K(this.wk);this.wk=new gvjs_2P(b,gvjs_Zy(this.fe.j()).width,gvjs__P(this.ec)?0:1);a.Ia(this.wk,!0);this.ec.addEventListener(this.wk,gvjs_Pp,this.iI,!1,this)};
gvjs_.rE=function(){for(var a=this.ec.Ig,b=0,c=this.fe.th();b<c;b++)a.ze(this.fe.td(b).di.getId())&&this.fe.td(b).Gb(!1);gvjs_3P(this.wk,a.Ka());this.fe.Va("");this.fe.Gb(!gvjs_0P(this.ec))};gvjs_.Xo=function(a){var b=a.item.getValue();a.item.Gb(!1);a.preventDefault();this.fe.QB();this.fe.Va("");this.ec.Ig.set(b.getId(),b);this.fe.Gb(!gvjs_0P(this.ec));gvjs_3P(this.wk,this.ec.Ig.Ka());gvjs_WP.o.Xo.call(this,a)};
gvjs_.iI=function(a){a=a.item;this.ec.Ig.remove(a.getId());this.fe.Gb(!0);for(var b=0,c=this.fe.th();b<c;b++)if(this.fe.td(b).di==a){this.fe.td(b).Gb(!0);break}this.ec.xu()};gvjs_.MY=function(){this.fe.Va("")};function gvjs_2P(a,b,c,d){gvjs_pB.call(this,d);this.vE=a;this.Zq=b;this.$_=c;this.Ez=0;this.oT=[]}gvjs_l(gvjs_2P,gvjs_pB);gvjs_2P.prototype.J=function(){var a=this.G.J("UL");this.H=a;this.Lf(a)};gvjs_2P.prototype.Qh=function(a){return"UL"==a.tagName};
gvjs_2P.prototype.Lf=function(a){gvjs_yB(a,"google-visualization-controls-categoryfilter-selected");this.vE==gvjs_GO?gvjs_yB(a,gvjs_T):("belowWrapping"==this.vE||this.vE==gvjs_HO)&&gvjs_I(a,gvjs_Bt,this.Zq+gvjs__)};
function gvjs_3P(a,b){a.Bc(!0);a.oT=[];a.Ez=b.length;for(var c=0;c<a.Ez;c++){var d=a,e=b[c];var f=new gvjs_MC(gvjs_Z,new gvjs_5P(d.vE));f.xp(!1);var g=new gvjs_IC("\u00d7",new gvjs_SP);gvjs_L(g,gvjs_Pp,gvjs_ub(d.iI,e,f),!1,d);f.Ia(g,!0);g.j().setAttribute(gvjs_Av,0);g.Gb(d.Ez>d.$_);d=new gvjs_oC(e.Fd());d.ds(gvjs_T);f.Ia(d,!0);a.oT.push(f);a.Ia(f,!0)}}
gvjs_2P.prototype.iI=function(a,b,c){this.Ez<=this.$_||(this.removeChild(c.target.getParent(),!0),gvjs_Vh(this.oT,b),this.Ez--,this.Ez<=this.$_&&0<this.Ez&&gvjs_m(this.oT,function(d){d.hf(0).Gb(!1)}),this.dispatchEvent(new gvjs_HP(gvjs_Pp,this,a)),c.stopPropagation())};function gvjs_5P(a){this.nM=void 0;this.vE=a}gvjs_l(gvjs_5P,gvjs_JC);gvjs_5P.prototype.J=function(a){var b=this.vE==gvjs_HO?"":gvjs_T;return a.xa().J("LI",this.Zl(a).join(" ")+" "+b)};gvjs_5P.prototype.Qh=function(a){return"LI"==a.tagName};function gvjs_6P(a){gvjs_zP.call(this,a)}gvjs_l(gvjs_6P,gvjs_zP);gvjs_6P.prototype.gt=function(){return"SelectorUi"};function gvjs_7P(a){gvjs_SO.call(this,a);this.Fe=null}gvjs_l(gvjs_7P,gvjs_rP);gvjs_7P.prototype.gt=function(){return"ChartRangeFilterUi"};gvjs_7P.prototype.pr=function(a,b,c){this.clear();this.Fe=gvjs_yP(a,b);b=a.Y(this.Fe);if(b==gvjs_e||b==gvjs_Ka)throw Error("The filter cannot operate on a column of type "+b+". Column type must be one of: number, date, datetime or timeofday. Column role must be domain, and correlate to a continuous axis.");c.__data__=a};
gvjs_7P.prototype.WF=function(a,b,c){a=new gvjs_Q(a);b=c.range;if(gvjs_qb(b)!=gvjs_d)return a;c=b.start;b=b.end;if(null==c&&null==b)return a;a.Dp(a.ht([{column:this.Fe,minValue:c,maxValue:b}]));return a};function gvjs_8P(a){gvjs_RO.call(this,a)}gvjs_l(gvjs_8P,gvjs_RO);gvjs_=gvjs_8P.prototype;gvjs_.dE=null;gvjs_.bK=null;gvjs_.Rv=null;gvjs_.O=function(){this.dE&&this.dE.Nb();gvjs_8P.o.O.call(this)};
gvjs_.getState=function(){function a(){return null===b.Rv?{}:{range:b.Rv.range}}var b=this;if(!this.dE)return a();var c=this.dE.IO();return null==c.start||null==c.end?a():{range:c}};gvjs_.draw=function(a,b){this.Rv=a;this.bK||(this.bK=new gvjs_R({chartType:"RangeSelector",dataTable:a.__data__,options:b,state:a,view:b.chartView}),gvjs_Xk(this.bK,gvjs_x,gvjs_k(this.tua,this)));this.bK.draw(this.getContainer())};gvjs_.tua=function(){this.dE=this.bK.vf();gvjs_Xk(this.dE,gvjs_xu,gvjs_k(this.sua,this))};
gvjs_.sua=function(a){gvjs_M(this,gvjs_MO,{startChanged:a.startChanged,endChanged:a.endChanged,inProgress:a.inProgress})};function gvjs_9P(a){gvjs_pP.call(this,a);this.$p=-1;this.fW=null}gvjs_l(gvjs_9P,gvjs_pP);gvjs_=gvjs_9P.prototype;gvjs_.NV=null;gvjs_.pf=null;gvjs_.Of=function(){return{columns:null}};gvjs_.em=function(a,b){a=gvjs_9P.o.em.call(this,a,b);a.values=this.pf;b=a.label;null==b&&(b=this.BO(),1<=b.length&&(b=b[0].Wa(),null!=this.$p&&(b=b.Ca(this.$p),a.label=b)));return a};
gvjs_.pr=function(a,b,c){this.clear();this.$p=b.Da("chartColumnIndex");this.NV=b.ob("chartColumnId");if(null==this.$p){if(null==this.NV)throw Error("Either chartColumnIndex or chartColumnId must be specified.");for(var d=a.Z(),e=0;e<d;e++)a.md(e)===this.NV&&(this.$p=e);if(null==this.$p||0>this.$p)throw Error("Invalid column id");}if(null==this.$p||0>this.$p)throw Error("Invalid column index");d=b.ea("columns");if(gvjs_Nh(d)&&d.length)this.pf=d;else{d={string:{string:!0},discrete:{string:!0},number:{number:!0},
dateortime:{date:!0,datetime:!0,timeofday:!0},continuous:{number:!0,date:!0,datetime:!0,timeofday:!0}};b=(b=gvjs_r(b,"columnType"))&&d[b];this.fW={};d=[];e=a.Z();for(var f=0;f<e;f++){var g=a.Ca(f),h=a.md(f),k=a.Y(f);if(!b||b[k])this.fW[g]={index:f,id:h,label:g},d.push(g)}this.pf=d}this.US=[{input:"dataColumnIndex",og:"view.columns."+this.$p}];this.HL(c)};
gvjs_.HL=function(a){a=a.selectedValues;if(null!=a&&(!gvjs_Nh(a)||1<a.length))throw Error("Invalid selectedValues: should be an array of length zero or one.");};gvjs_.XU=function(a,b,c){var d=c.selectedValues;return gvjs_Nh(d)&&1===d.length?(c.dataColumnIndex=this.fW[d[0]].index,gvjs_9P.o.XU.call(this,a,b,c)):a};function gvjs_$P(a){gvjs_9P.call(this,a)}gvjs_l(gvjs_$P,gvjs_9P);gvjs_$P.prototype.gt=function(){return"SelectorUi"};var gvjs_1ia={day:864E5,hour:36E5,minute:6E4,second:1E3,millisecond:1};function gvjs_aQ(a){var b=gvjs_bQ(a);var c=a.split(" ");if(2===c.length){if(c=Number(c[0]),typeof c!==gvjs_c||isNaN(c))throw Error('Invalid number for increment: "'+a+'".');}else c=1;b=gvjs_1ia[b];if(!b)throw Error('Invalid number for increment "'+a+'".');return c*b}function gvjs_bQ(a){var b=a.length-1;a="s"===a.charAt(b)?a.substring(0,b):a;a=a.split(" ");return 2===a.length?a[1]:a[0]}
function gvjs_cQ(a,b,c){a=Number(a);b=(a-c)%gvjs_aQ(b);return a=new Date(a-b)}function gvjs_dQ(a,b,c){a=Number(a);c=a-c;b=gvjs_aQ(b);c%=b;return a=0===c?new Date(a):new Date(a+b-c)};function gvjs_eQ(a){gvjs_vP.call(this,a);this.Bj=this.Pb=null}gvjs_l(gvjs_eQ,gvjs_vP);gvjs_=gvjs_eQ.prototype;gvjs_.z4=function(){var a=this.Mc.getValue()+this.Xp,b=a+this.Mc.am();this.dw&&gvjs_0c(this.dw,this.Pb.ac(new Date(a)));this.Nv&&gvjs_0c(this.Nv,this.Pb.ac(new Date(b)))};gvjs_.h1=function(a){var b=a.nb(gvjs_ks);(a=String(a.ea("step")))&&!b.pattern&&(b.pattern=gvjs_2ia[gvjs_bQ(a)]);this.Pb=new gvjs_fe(b)};
gvjs_.draw=function(a,b){b=b||{};var c=new gvjs_qd([b,gvjs_fQ]);(b=gvjs_BP(b))||(b=new gvjs_pB);b.W(this.getContainer());var d=gvjs_r(c,"cssClass");d&&gvjs_yB(b.j(),d);gvjs_xP(this,b,a,c,gvjs_fQ)};gvjs_.dfa=function(a){this.Bj=String(a.ea("step",gvjs_fQ.step));var b=gvjs_aQ(this.Bj);this.Mc.SS(b);b=gvjs_aQ(String(a.ea("unitIncrement",gvjs_fQ.unitIncrement)));this.Mc.LA=b;a=gvjs_aQ(String(a.ea(gvjs_IO,gvjs_fQ.blockIncrement)));this.Mc.Rm=a};gvjs_.uY=function(a,b){return a.Da(b)};
gvjs_.Bda=function(a,b,c){var d=String(this.Bj);a=new Date(a);var e=gvjs_bQ(d);a=gvjs_cQ(a,e,Number(new Date(1970,0,1))).valueOf();b=gvjs_dQ(new Date(b),d,a).valueOf();c.lowValue=gvjs_cQ(new Date(c.lowValue),d,a).valueOf();c.highValue=gvjs_dQ(new Date(c.highValue),d,a).valueOf();return{minValue:a,maxValue:b,state:c}};gvjs_.getState=function(){var a=gvjs_eQ.o.getState.call(this);a.lowValue&&(a.lowValue=new Date(a.lowValue.valueOf()));a.highValue&&(a.highValue=new Date(a.highValue.valueOf()));return a};
var gvjs_2ia={year:"yyyy",month:"yyyy-MM",day:"yyyy-MM-dd",hour:gvjs_OO,minute:gvjs_OO,second:"yy/MM/dd hh:mm:ssa",millisecond:"yy/MM/dd hh:mm:ss:SSSSa"},gvjs_fQ={showRangeValues:!0,minValue:null,maxValue:null,cssClass:gvjs_JO,step:"day",unitIncrement:"day",blockIncrement:"day",orientation:gvjs_Z};function gvjs_gQ(a){gvjs_sP.call(this,a)}gvjs_l(gvjs_gQ,gvjs_sP);gvjs_=gvjs_gQ.prototype;gvjs_.gt=function(){return"DateRangeFilterUi"};gvjs_.em=function(a,b){a=gvjs_gQ.o.em.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Bb;null==a.label&&(a.label=this.Bq);return a};gvjs_.xZ=function(a,b){this.NS(gvjs_t(b,gvjs_Dg,gvjs_hQ(this,a,gvjs_Jt)));this.MS(gvjs_t(b,gvjs_Cg,gvjs_hQ(this,a,gvjs_At)))};
gvjs_.pr=function(a,b,c){this.clear();this.Fe=gvjs_yP(a,b);this.Bq=a.Ca(this.Fe);var d=a.Y(this.Fe);if(d!=gvjs_Oa&&d!=gvjs_Pa)throw Error(gvjs_Oe+this.Fe+" is not a date");this.xZ(a,b);gvjs_tP(this,c)};function gvjs_hQ(a,b,c){a=b.Zj(a.Fe)[c];return Number(a)}gvjs_.M4=function(a){return Number(a)};gvjs_.getState=function(){var a=gvjs_gQ.o.getState.call(this);a.lowValue&&(a.lowValue=new Date(a.lowValue.valueOf()));a.highValue&&(a.highValue=new Date(a.highValue.valueOf()));return a};
gvjs_.oY=function(a,b,c){(a=gvjs_Zw(a,"ui",{}).step)||(a="day");return function(d){d=Number(d);return b<=d&&c>=d}};function gvjs_iQ(a){gvjs_RO.call(this,a);this.K={}}gvjs_l(gvjs_iQ,gvjs_RO);gvjs_iQ.prototype.draw=function(a){this.K=a};gvjs_iQ.prototype.getState=function(){return this.K};function gvjs_jQ(a){gvjs_sP.call(this,a)}gvjs_l(gvjs_jQ,gvjs_sP);gvjs_=gvjs_jQ.prototype;gvjs_.gt=function(){return"NumberRangeUi"};gvjs_.em=function(a,b){a=gvjs_jQ.o.em.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Bb;null==a.label&&(a.label=this.Bq);return a};gvjs_.xZ=function(a,b){this.NS(gvjs_t(b,gvjs_Dg,a.Zj(this.Fe).min));this.MS(gvjs_t(b,gvjs_Cg,a.Zj(this.Fe).max))};
gvjs_.pr=function(a,b,c){this.clear();this.Fe=gvjs_yP(a,b);this.Bq=a.Ca(this.Fe);if(a.Y(this.Fe)!==gvjs_c)throw Error(gvjs_Oe+this.Fe+" is not numeric");this.xZ(a,b);gvjs_tP(this,c)};gvjs_.M4=function(a){return gvjs_fc(String(a))};gvjs_.oY=function(a,b,c){(a=gvjs_Zw(a,"ui",{}).step)||(a=1);return function(d){return b<=d&&c>=d}};function gvjs_kQ(a){gvjs_vP.call(this,a);this.Bj=this.Pb=null;this.On=0}gvjs_l(gvjs_kQ,gvjs_vP);gvjs_=gvjs_kQ.prototype;gvjs_.z4=function(){var a=this.Mc.getValue()+this.Xp,b=a+this.Mc.am();a/=this.On;b/=this.On;this.dw&&gvjs_0c(this.dw,this.Pb.ac(a));this.Nv&&gvjs_0c(this.Nv,this.Pb.ac(b))};gvjs_.h1=function(a){var b=a.nb(gvjs_ks);(a=Number(a.Da("step")))&&null==b.fractionDigits&&(b.fractionDigits=a);this.Pb=new gvjs_je(b)};
gvjs_.draw=function(a,b){b=b||{};var c=new gvjs_qd([b,gvjs_lQ]);(b=gvjs_BP(b))||(b=new gvjs_pB);b.W(this.getContainer());var d=gvjs_r(c,"cssClass");d&&gvjs_yB(b.j(),d);gvjs_xP(this,b,a,c,gvjs_lQ)};
gvjs_.dfa=function(a){var b=gvjs_lQ.step,c=a.Da(gvjs_Hv);null!=c&&(c=Math.max(2,c),b=(this.Mc.xf()-this.Mc.yf())/c);b=Number(gvjs_t(a,"step",b));c=gvjs_t(a,"unitIncrement",gvjs_lQ.unitIncrement);a=gvjs_t(a,gvjs_IO,gvjs_lQ.blockIncrement);this.On=Math.pow(10,gvjs_eE(b));b=Math.round(b*this.On);c=Math.round(c*this.On);a=Math.round(a*this.On);this.Mc.SS(b);this.Mc.LA=c;this.Mc.Rm=a;this.Bj=b};gvjs_.uY=function(a,b){return a.Da(b)};
gvjs_.Bda=function(a,b,c){var d=this.Bj;a=Math.floor(a*this.On);a-=(a-0)%d;b=gvjs_mQ(Math.ceil(b*this.On),d,a);var e=c.lowValue*this.On;c.lowValue=e-(e-a)%d;c.highValue=gvjs_mQ(c.highValue*this.On,d,a);return{minValue:a,maxValue:b,state:c}};
gvjs_.getState=function(){var a=this.Mc;if(!a)return{lowValue:null,highValue:null,lowThumbAtMinimum:null,highThumbAtMaxium:null};var b=a.getValue(),c=a.am();return{lowValue:(b+this.Xp)/this.On,highValue:(b+c+this.Xp)/this.On,lowThumbAtMinimum:b===a.yf(),highThumbAtMaximum:b+c===a.xf()}};function gvjs_mQ(a,b,c){c=(a-c)%b;return 0===c?a:a+b-c}var gvjs_lQ={showRangeValues:!0,minValue:null,maxValue:null,ticks:null,cssClass:gvjs_JO,format:{},step:1,unitIncrement:1,blockIncrement:10,orientation:gvjs_Z};function gvjs_nQ(a){gvjs_pP.call(this,a)}gvjs_l(gvjs_nQ,gvjs_qP);gvjs_nQ.prototype.gt=function(){return"NumberRangeUi"};function gvjs_oQ(a){gvjs_SO.call(this,a);this.Fe=-1}gvjs_l(gvjs_oQ,gvjs_rP);gvjs_=gvjs_oQ.prototype;gvjs_.Bq=null;gvjs_.Of=function(){return{matchType:gvjs_Ya,caseSensitive:!1,useFormattedValue:!1}};gvjs_.em=function(a,b){a=gvjs_oQ.o.em.call(this,a,b);null==a.label&&(a.label=this.Bq);return a};gvjs_.pr=function(a,b){this.clear();this.Fe=gvjs_yP(a,b);this.Bq=a.Ca(this.Fe)};
gvjs_.WF=function(a,b,c){var d=gvjs_s(b,"caseSensitive"),e=gvjs_r(b,"matchType");gvjs_s(b,"prefixMatch");var f=gvjs_s(b,gvjs_NO),g=this.Fe;b=[];c=c.value.toString();if(!c)return new gvjs_Q(a);d||(c=c.toLowerCase());for(var h=0;h<a.aa();h++){var k=f?a.Ga(h,g):""+a.getValue(h,g);d||(k=k.toLowerCase());switch(e){case "exact":k==c&&b.push(h);break;case "any":-1!=k.indexOf(c)&&b.push(h);break;default:0==k.indexOf(c)&&b.push(h)}}a=new gvjs_Q(a);a.Dp(b);return a};
function gvjs_pQ(a){gvjs_oQ.call(this,a)}gvjs_l(gvjs_pQ,gvjs_oQ);gvjs_pQ.prototype.gt=function(){return"StringFilterUi"};function gvjs_qQ(a){gvjs_RO.call(this,a);this.Hm=0}gvjs_l(gvjs_qQ,gvjs_RO);gvjs_=gvjs_qQ.prototype;gvjs_.Sf=null;gvjs_.getState=function(){return{value:this.Sf?this.Sf.value:null}};
gvjs_.draw=function(a,b){b=b||{};var c=gvjs_BP(b);c||(c=new gvjs_pB);c.W(this.getContainer());var d=b.cssClass?String(b.cssClass):"google-visualization-controls-stringfilter";gvjs_yB(c.j(),d);this.Sf=this.rW(a,b);c.ib().appendChild(this.Sf)};
gvjs_.rW=function(a,b){var c=gvjs_F(gvjs_oa);c.setAttribute(gvjs_ug,gvjs_nh(this.getContainer())+"-input");gvjs_6g in a&&a.value&&(c.value=String(a.value));gvjs_LO in b&&c.setAttribute(gvjs_LO,b.placeholder);"realtimeTrigger"in b&&!b.realtimeTrigger?(this.addEventListener(c,gvjs_$s,this.taa,!1,this),this.addEventListener(c,gvjs_Jq,this.xu,!1,this)):this.addEventListener(c,gvjs_at,this.taa);return c};
gvjs_.taa=function(a){this.Hm&&gvjs_2l(this.Hm);13==a.keyCode?(this.xu(),a.preventDefault()):this.Hm=gvjs_1l(function(){this.Hm=0;this.xu()},200,this)};gvjs_.xu=function(){gvjs_M(this,gvjs_MO,null)};gvjs_h("google.visualization.Choreographer",gvjs_wn,void 0);gvjs_wn.prototype.bind=gvjs_wn.prototype.bind;gvjs_wn.prototype.clear=gvjs_wn.prototype.clear;gvjs_wn.prototype.dispose=gvjs_wn.prototype.na;gvjs_wn.prototype.isDisposed=gvjs_wn.prototype.Cg;gvjs_wn.prototype.draw=gvjs_wn.prototype.draw;gvjs_h(gvjs_Vf,gvjs_In,void 0);gvjs_In.prototype.bind=gvjs_In.prototype.bind;gvjs_In.prototype.getSelection=gvjs_In.prototype.getSelection;gvjs_In.prototype.clear=gvjs_In.prototype.clear;
gvjs_In.prototype.dispose=gvjs_In.prototype.na;gvjs_In.prototype.isDisposed=gvjs_In.prototype.Cg;gvjs_In.prototype.draw=gvjs_In.prototype.draw;gvjs_h("google.visualization.Control",gvjs_SO,void 0);gvjs_SO.prototype.draw=gvjs_SO.prototype.draw;gvjs_SO.prototype.getState=gvjs_SO.prototype.getState;gvjs_SO.prototype.resetControl=gvjs_SO.prototype.Yt;gvjs_SO.prototype.clear=gvjs_SO.prototype.clear;gvjs_SO.prototype.dispose=gvjs_SO.prototype.na;gvjs_SO.prototype.isDisposed=gvjs_SO.prototype.Cg;
gvjs_h(gvjs_Yf,gvjs_rP,void 0);gvjs_rP.prototype.applyFilter=gvjs_rP.prototype.hB;gvjs_h(gvjs_dg,gvjs_mP,void 0);gvjs_mP.prototype.applyOperator=gvjs_mP.prototype.XF;gvjs_h("google.visualization.ControlUi",gvjs_RO,void 0);gvjs_RO.prototype.draw=gvjs_RO.prototype.draw;gvjs_RO.prototype.getState=gvjs_RO.prototype.getState;gvjs_RO.prototype.clear=gvjs_RO.prototype.clear;gvjs_RO.prototype.dispose=gvjs_RO.prototype.na;gvjs_RO.prototype.isDisposed=gvjs_RO.prototype.Cg;gvjs_h(gvjs_lg,gvjs_pQ,void 0);
gvjs_pQ.prototype.draw=gvjs_pQ.prototype.draw;gvjs_pQ.prototype.applyFilter=gvjs_pQ.prototype.hB;gvjs_pQ.prototype.getState=gvjs_pQ.prototype.getState;gvjs_pQ.prototype.resetControl=gvjs_pQ.prototype.Yt;gvjs_pQ.prototype.clear=gvjs_pQ.prototype.clear;gvjs_pQ.prototype.dispose=gvjs_pQ.prototype.na;gvjs_pQ.prototype.isDisposed=gvjs_pQ.prototype.Cg;gvjs_h(gvjs_mg,gvjs_qQ,void 0);gvjs_qQ.prototype.draw=gvjs_qQ.prototype.draw;gvjs_qQ.prototype.getState=gvjs_qQ.prototype.getState;
gvjs_qQ.prototype.clear=gvjs_qQ.prototype.clear;gvjs_qQ.prototype.isDisposed=gvjs_qQ.prototype.Cg;gvjs_h(gvjs_cg,gvjs_jQ,void 0);gvjs_jQ.prototype.draw=gvjs_jQ.prototype.draw;gvjs_jQ.prototype.applyFilter=gvjs_jQ.prototype.hB;gvjs_jQ.prototype.getState=gvjs_jQ.prototype.getState;gvjs_jQ.prototype.resetControl=gvjs_jQ.prototype.Yt;gvjs_jQ.prototype.clear=gvjs_jQ.prototype.clear;gvjs_jQ.prototype.dispose=gvjs_jQ.prototype.na;gvjs_jQ.prototype.isDisposed=gvjs_jQ.prototype.Cg;gvjs_h(gvjs_Wf,gvjs_gQ,void 0);
gvjs_gQ.prototype.draw=gvjs_gQ.prototype.draw;gvjs_gQ.prototype.applyFilter=gvjs_gQ.prototype.hB;gvjs_gQ.prototype.getState=gvjs_gQ.prototype.getState;gvjs_gQ.prototype.resetControl=gvjs_gQ.prototype.Yt;gvjs_gQ.prototype.clear=gvjs_gQ.prototype.clear;gvjs_gQ.prototype.dispose=gvjs_gQ.prototype.na;gvjs_gQ.prototype.isDisposed=gvjs_gQ.prototype.Cg;gvjs_h("google.visualization.NumberRangeUi",gvjs_kQ,void 0);gvjs_kQ.prototype.draw=gvjs_kQ.prototype.draw;gvjs_kQ.prototype.getState=gvjs_kQ.prototype.getState;
gvjs_kQ.prototype.clear=gvjs_kQ.prototype.clear;gvjs_kQ.prototype.dispose=gvjs_kQ.prototype.na;gvjs_kQ.prototype.isDisposed=gvjs_kQ.prototype.Cg;gvjs_h("google.visualization.DateRangeFilterUi",gvjs_eQ,void 0);gvjs_eQ.prototype.draw=gvjs_eQ.prototype.draw;gvjs_eQ.prototype.getState=gvjs_eQ.prototype.getState;gvjs_eQ.prototype.clear=gvjs_eQ.prototype.clear;gvjs_eQ.prototype.dispose=gvjs_eQ.prototype.na;gvjs_eQ.prototype.isDisposed=gvjs_eQ.prototype.Cg;
gvjs_h("google.visualization.NumberRangeSetter",gvjs_nQ,void 0);gvjs_nQ.prototype.draw=gvjs_nQ.prototype.draw;gvjs_nQ.prototype.apply=gvjs_nQ.prototype.apply;gvjs_nQ.prototype.getState=gvjs_nQ.prototype.getState;gvjs_nQ.prototype.resetControl=gvjs_nQ.prototype.Yt;gvjs_nQ.prototype.clear=gvjs_nQ.prototype.clear;gvjs_nQ.prototype.dispose=gvjs_nQ.prototype.na;gvjs_nQ.prototype.isDisposed=gvjs_nQ.prototype.Cg;gvjs_h("google.visualization.ColumnSelector",gvjs_$P,void 0);gvjs_$P.prototype.draw=gvjs_$P.prototype.draw;
gvjs_$P.prototype.apply=gvjs_$P.prototype.apply;gvjs_$P.prototype.getState=gvjs_$P.prototype.getState;gvjs_$P.prototype.resetControl=gvjs_$P.prototype.Yt;gvjs_$P.prototype.clear=gvjs_$P.prototype.clear;gvjs_$P.prototype.dispose=gvjs_$P.prototype.na;gvjs_$P.prototype.isDisposed=gvjs_$P.prototype.Cg;gvjs_h(gvjs_Of,gvjs_6P,void 0);gvjs_6P.prototype.draw=gvjs_6P.prototype.draw;gvjs_6P.prototype.applyFilter=gvjs_6P.prototype.hB;gvjs_6P.prototype.getState=gvjs_6P.prototype.getState;
gvjs_6P.prototype.resetControl=gvjs_6P.prototype.Yt;gvjs_6P.prototype.clear=gvjs_6P.prototype.clear;gvjs_6P.prototype.dispose=gvjs_6P.prototype.na;gvjs_6P.prototype.isDisposed=gvjs_6P.prototype.Cg;gvjs_h("google.visualization.SelectorUi",gvjs_UP,void 0);gvjs_UP.prototype.draw=gvjs_UP.prototype.draw;gvjs_UP.prototype.getState=gvjs_UP.prototype.getState;gvjs_UP.prototype.clear=gvjs_UP.prototype.clear;gvjs_UP.prototype.dispose=gvjs_UP.prototype.na;gvjs_UP.prototype.isDisposed=gvjs_UP.prototype.Cg;
gvjs_h(gvjs_Pf,gvjs_7P,void 0);gvjs_7P.prototype.draw=gvjs_7P.prototype.draw;gvjs_7P.prototype.applyFilter=gvjs_7P.prototype.hB;gvjs_7P.prototype.getState=gvjs_7P.prototype.getState;gvjs_7P.prototype.resetControl=gvjs_7P.prototype.Yt;gvjs_7P.prototype.clear=gvjs_7P.prototype.clear;gvjs_7P.prototype.dispose=gvjs_7P.prototype.na;gvjs_7P.prototype.isDisposed=gvjs_7P.prototype.Cg;gvjs_h(gvjs_Qf,gvjs_8P,void 0);gvjs_8P.prototype.draw=gvjs_8P.prototype.draw;gvjs_8P.prototype.getState=gvjs_8P.prototype.getState;
gvjs_8P.prototype.clear=gvjs_8P.prototype.clear;gvjs_8P.prototype.dispose=gvjs_8P.prototype.na;gvjs_8P.prototype.isDisposed=gvjs_8P.prototype.Cg;gvjs_h("google.visualization.HeadlessUi",gvjs_iQ,void 0);gvjs_iQ.prototype.draw=gvjs_iQ.prototype.draw;gvjs_iQ.prototype.getState=gvjs_iQ.prototype.getState;gvjs_iQ.prototype.clear=gvjs_iQ.prototype.clear;gvjs_iQ.prototype.dispose=gvjs_iQ.prototype.na;gvjs_iQ.prototype.isDisposed=gvjs_iQ.prototype.Cg;gvjs_h(gvjs_Xf,gvjs_nP,void 0);
gvjs_nP.prototype.draw=gvjs_nP.prototype.draw;gvjs_nP.prototype.applyOperator=gvjs_nP.prototype.XF;gvjs_nP.prototype.getState=gvjs_nP.prototype.getState;gvjs_nP.prototype.resetControl=gvjs_nP.prototype.Yt;gvjs_nP.prototype.clear=gvjs_nP.prototype.clear;gvjs_nP.prototype.dispose=gvjs_nP.prototype.na;gvjs_nP.prototype.isDisposed=gvjs_nP.prototype.Cg;gvjs_h("google.visualization.DrilldownOperatorUi",gvjs_oP,void 0);gvjs_oP.prototype.draw=gvjs_oP.prototype.draw;gvjs_oP.prototype.getState=gvjs_oP.prototype.getState;
gvjs_oP.prototype.clear=gvjs_oP.prototype.clear;gvjs_oP.prototype.dispose=gvjs_oP.prototype.na;gvjs_oP.prototype.isDisposed=gvjs_oP.prototype.Cg;gvjs_h("google.visualization.drawDrilldown",function(a,b,c){var d=new gvjs_lP(a);gvjs_L(c,gvjs_0q,function(){d.rollup()});d.draw(b)},void 0);gvjs_h("google.visualization.RemoteDataSource",gvjs_gP,void 0);gvjs_gP.prototype.getUrl=gvjs_gP.prototype.getUrl;gvjs_gP.prototype.getColumnId=gvjs_gP.prototype.md;gvjs_gP.prototype.getColumnType=gvjs_gP.prototype.Y;
gvjs_gP.prototype.getNumberOfColumns=gvjs_gP.prototype.Z;
